name: Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install lab
        run: pip install jupyterlab
      - name: build js
        run: (cd js && npm install && npm run build:labextension)
      - name: Package
        run: python setup.py bdist_wheel --universal
      - name: Test Package
        run: pip install dist/*.whl && python -c "import ipyaggrid"
      - uses: actions/upload-artifact@v1
        with:
          name: dist-${{ github.run_number }}
          path: ./dist
